#!/bin/bash
# ifstest

SPACES="1 2 3 4 5 6"
GRTR="1<2<3<4"
COMMA="1,2,3,4,5,6"
PIPES="1|2|3|4|5|6 7|8|9"

for y in $SPACES
  do
   echo "this is SPACES" $y
  done
echo $SPACES

IFS="<"
for x in $GRTR
  do
   echo "this is GRTR" $x
  done
echo $GRTR
unset IFS

IFS=","
for r in $COMMA
   do
     echo "this is COMMA " $r
   done
unset IFS


IFS="|"
for z in $PIPES
  do
   echo "this is PIPES" $z
  done
unset IFS

for a in $PIPES
  do
    echo "this is PIPES after unset "$a
  done

