#!/bin/bash
# days_alive
# lab 5
# torresm

# today
EDATE=$(date +%s)
# date of birth
SDATE=$(date -d '09/21/1992' +%s)
# seconds alive
SALIVE=$(($EDATE - $SDATE))
# days alive
DALIVE=$(($SALIVE/86400))
# ten thousand days from date of birth
TENDAYS=$((SDATE + 864000000))
# ten thousand days from date of birth in MM/DD/CCYY
TDATE=$(date -d '@'$TENDAYS'' +%m/%d/%Y)

##echo "You have been alive $SALIVE seconds."
echo "You have been alive" $DALIVE "days."
echo "10000 days for you is" $TDATE
